services:
  kvrocks:
    image: apache/kvrocks:2.11.0
    volumes:
      - kvrocks_data_volume:/kvrocks_data
    ports:
      - 6666:6666  # TODO remove on final version

volumes:
  kvrocks_data_volume: