services:
  fastapi:
    build: .
    environment:
      - WEB_CONCURRENCY=4  # set uvicorn workers
      - KVROCKS_URL=redis://kvrocks:6666
    ports:
      - 80:80
    depends_on:
      - kvrocks

  kvrocks:
    image: apache/kvrocks:2.11.0
    volumes:
      - kvrocks_data_volume:/kvrocks_data

volumes:
  kvrocks_data_volume: